In [1]:
#!pip install flask
from flask import Flask

In [4]:
# import numpy as np
# from sklearn.linear_model import LinearRegression 
# reg = LinearRegression() Instance
# reg.fit(X, y) Method
# reg.predict(np.array([[3, 5]]))
#This is just for your refrence 

In [5]:
# Intialization of Flask
app = Flask(__name__)# It takes care of your dir structure to render Html pages and css from specific folder

@app.route("/") # It binds the wrbiste url with below fuction 
def hello():
    return "Hello Everyone"

if __name__=="__main__":
    app.run()

 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)


In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/main/hiring.csv")
df.head()

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [7]:
df.shape

(8, 4)

In [8]:
df.isnull().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [9]:
df.experience.fillna(0,inplace=True)

In [10]:
df.head()

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [11]:
df.test_score.fillna(df.test_score.mean(),inplace=True)

In [12]:
df.isnull().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

# Dataset is clean and I can make a ML model on top of it

In [13]:
df

experience  test_score  interview_score  salary
0          0    8.000000                9   50000
1          0    8.000000                6   45000
2       five    6.000000                7   60000
3        two   10.000000               10   65000
4      seven    9.000000                6   70000
5      three    7.000000               10   62000
6        ten    7.857143                7   72000
7     eleven    7.000000                8   80000

In [14]:
X = df.iloc[:,:-1]

In [15]:
X.shape

(8, 3)

In [16]:
X

experience  test_score  interview_score
0          0    8.000000                9
1          0    8.000000                6
2       five    6.000000                7
3        two   10.000000               10
4      seven    9.000000                6
5      three    7.000000               10
6        ten    7.857143                7
7     eleven    7.000000                8

In [17]:
def conv_dict(x):
    dict = {
        "five":5,
        "two":2,
        "seven":7,
        "three":3,
        "ten":10,
        "eleven":11,
        0:0
    }
    return dict[x]

In [18]:
X.experience = X.experience.apply(conv_dict)

In [19]:
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [20]:
y = df.iloc[:,-1]

In [21]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64


# I am not doing the train and test split
# But I would encourage all of you to do it on your dataset

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
X.iloc[0]

experience         0.0
test_score         8.0
interview_score    9.0
Name: 0, dtype: float64

In [24]:
lr = LinearRegression()
lr

LinearRegression()

In [25]:
lr.fit(X,y)

LinearRegression()

In [26]:
y_pred = lr.predict(X)

In [27]:
y_pred

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [28]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [29]:
lr.predict([[7,6,9]])

array([68281.17462588])

In [30]:
lr.predict([[7,6,9]])

array([68281.17462588])

In [31]:
import pickle
pickle.dump(lr,open('c_31_lr_model.pkl','wb'))
#dump will save your model on given name
# wb - write binary modes

In [1]:
lr.predict([[7,6,9]])

NameError: name 'lr' is not defined

In [2]:
import pickle
lr = pickle.load(open("c_31_lr_model.pkl","rb"))
lr

LinearRegression()

In [3]:
lr.predict([[7,6,9]])

array([68281.17462588])