In [14]:
import pandas as pd
import numpy as np

In [15]:
a = [[20,50,4], [26,60,5], [30,65,5.5], [40,75,7]]
b = ['Age', 'Weight', 'Height']
A = pd.DataFrame(a, columns = b)
A

Age  Weight  Height
0   20      50     4.0
1   26      60     5.0
2   30      65     5.5
3   40      75     7.0

In [16]:
100*np.var(A)/sum(np.var(A))

Age       39.136956
Weight    59.997692
Height     0.865351
dtype: float64

**Mean Centering**

In [17]:
M = np.mean(A)

In [18]:
M

Age       29.000
Weight    62.500
Height     5.375
dtype: float64

In [19]:
C  = A-M

In [20]:
C

Age  Weight  Height
0  -9.0   -12.5  -1.375
1  -3.0    -2.5  -0.375
2   1.0     2.5   0.125
3  11.0    12.5   1.625

In [21]:
C.T

0      1      2       3
Age     -9.000 -3.000  1.000  11.000
Weight -12.500 -2.500  2.500  12.500
Height  -1.375 -0.375  0.125   1.625

**Covariance Matrix**

In [22]:
help(np.cov)

Help on function cov in module numpy:

cov(m, y=None, rowvar=True, bias=False, ddof=None, fweights=None, aweights=None, *, dtype=None)
    Estimate a covariance matrix, given data and weights.
    
    Covariance indicates the level to which two variables vary together.
    If we examine N-dimensional samples, :math:`X = [x_1, x_2, ... x_N]^T`,
    then the covariance matrix element :math:`C_{ij}` is the covariance of
    :math:`x_i` and :math:`x_j`. The element :math:`C_{ii}` is the variance
    of :math:`x_i`.
    
    See the notes for an outline of the algorithm.
    
    Parameters
    ----------
    m : array_like
        A 1-D or 2-D array containing multiple variables and observations.
        Each row of `m` represents a variable, and each column a single
        observation of all those variables. Also see `rowvar` below.
    y : array_like, optional
        An additional set of variables and observations. `y` has the same form
        as that of `m`.
    rowvar : bool, optio

In [23]:
V = np.cov(C.T)

In [24]:
V

array([[ 70.66666667,  86.66666667,  10.5       ],
       [ 86.66666667, 108.33333333,  12.91666667],
       [ 10.5       ,  12.91666667,   1.5625    ]])

In [25]:
evalue, B = np.linalg.eig(V)

In [26]:
B

array([[-0.62486143, -0.77080323, -0.12413931],
       [-0.77517499,  0.63146152, -0.01897568],
       [-0.09301572, -0.08437252,  0.99208334]])

In [27]:
Binv = np.linalg.inv(B)

In [28]:
Binv

array([[-0.62486143, -0.77517499, -0.09301572],
       [-0.77080323,  0.63146152, -0.08437252],
       [-0.12413931, -0.01897568,  0.99208334]])

In [29]:
C

Age  Weight  Height
0  -9.0   -12.5  -1.375
1  -3.0    -2.5  -0.375
2   1.0     2.5   0.125
3  11.0    12.5   1.625

In [30]:
r1 = Binv@C.T

In [31]:
Anew = r1.T

In [32]:
Anew

0         1         2
0  15.441337 -0.840028 -0.009665
1   3.847403  0.765396  0.047826
2  -2.574426  0.797304 -0.047568
3 -16.714314 -0.722672  0.009407

In [33]:
Anew.columns = ['PC1', 'PC2', 'PC3']

In [34]:
Anew

PC1       PC2       PC3
0  15.441337 -0.840028 -0.009665
1   3.847403  0.765396  0.047826
2  -2.574426  0.797304 -0.047568
3 -16.714314 -0.722672  0.009407

In [35]:
100*np.var(Anew)/sum(np.var(Anew))

PC1    99.546942
PC2     0.452184
PC3     0.000874
dtype: float64