In [2]:
import numpy as np

## Notes

## **numpy** 
- is immutable, homogeneous array (stores same data type) in contiguous memory
- NumPy - ‘Numerical Python’ is meant for scientific calculations. 
- numpy is not a base python module. It is 3rd party module
- Can hold data of types - int, float, string
- Advantages over lists:
    - Allow you to operate over the entire data, unlike lists
    - Speed of execution
- Creating NumPy Arrays
    - Convert lists or tuples to arrays using np.array
    - Initialise fixed-length arrays using the NumPy functions
- np.array(p)
- len, size, itemsize, shape, ndim, dtype
- indexing --> single element --> np_2d[row index, col index]
- slicing --> many elements --> np_2d[row range, col range] 
    - where range = [start:end (excluded):skip] 
- np_2[2] = np_2d[2,] = np_2d[2,:]
- conditional subset
- Built-in functions: min, max, mean, power, absolute, sin, cos, tan, exp, exp2, log
- Aggregates: np.add.reduce(x), np.add.accumulate(x), np.multiply.accumulate(x)
- axis = 0 --> row; axis = 1 --> column
- Creating numpy arrays
    - np.ones() --> np.ones((5,3))
    - np.zeros()
    - np.random.randint() : 1D array --> np.random.randint(3,5, size=10)
    - np.random.random() : nD array --> np.random.random([3,4])
    - np.arange(start,end (excluded),skip): It is used to create an array with increments of fixed step size. --> np.arange(3,35,2)
    - np.linspace(): It is used to create an array of fixed length.
- Reshape: reshape(3,3)
- Stacking operations: np.hstack(), np.vstack()
- Linear Algebra: np.linalg.det(A), np.linalg.inv(A), np.matmul(A,B), np.linalg.matrix_power(A,3)


## Difference between len, size, shape, dim

In [3]:
p = [[1, 5, 4, 5],
    [3, 7, 8, 7],
    [4, 9, 4, 6]]
arr = np.array(p)
print(arr)
print(type(arr))
print("len:", len(arr))
print("size:", arr.size)
print("itemsize:", arr.itemsize, "bytes")
print("Memory consumption:", arr.size * arr.itemsize, "bytes")
print("shape:", arr.shape)
print("ndim:", arr.ndim)

[[1 5 4 5]
 [3 7 8 7]
 [4 9 4 6]]
<class 'numpy.ndarray'>
len: 3
size: 12
itemsize: 8 bytes
Memory consumption: 96 bytes
shape: (3, 4)
ndim: 2


In [8]:
# Conditional subset
print(arr < 5)
arr[arr < 5]

[[ True False  True False]
 [ True False False False]
 [ True False  True False]]


array([1, 4, 3, 4, 4])

In [27]:
arr = np.reshape(arr, (3, 4))
print(arr)
print("len:", len(arr))
print("size:", arr.size)
print("shape:", arr.shape)
print("ndim:", arr.ndim)

[[1 5 4 5]
 [3 7 8 7]
 [4 9 4 6]]
len: 3
size: 12
shape: (3, 4)
ndim: 2


In [28]:
arr = np.reshape(arr, (4, 3))
print(arr)
print("len:", len(arr))
print("size:", arr.size)
print("shape:", arr.shape)
print("ndim:", arr.ndim)

[[1 5 4]
 [5 3 7]
 [8 7 4]
 [9 4 6]]
len: 4
size: 12
shape: (4, 3)
ndim: 2


In [30]:
print(arr[1])
print(arr[1,])
print(arr[1,:])

[5 3 7]
[5 3 7]
[5 3 7]


In [32]:
print(arr[:,1])
print(arr[:,[1]])

[5 3 7 4]
[[5]
 [3]
 [7]
 [4]]


In [19]:
arr_3d = np.reshape(arr, (2, 3 , 2))
print(arr_3d)
print("len:", len(arr_3d))
print("size:", arr_3d.size)
print("shape:", arr_3d.shape)
print("ndim:", arr_3d.ndim)

[[[1 5]
  [4 5]
  [3 7]]

 [[8 7]
  [4 9]
  [4 6]]]
len: 2
size: 12
shape: (2, 3, 2)
ndim: 3


In [5]:
p = [[1, 5, 4, 5],
 [3, 7, 8, 7],
 [4, 9, 4, 6]]
arr = np.array(p)
print(id(arr), arr)

140659902935760 [[1 5 4 5]
 [3 7 8 7]
 [4 9 4 6]]


In [6]:
print(arr[0,0])
arr[0,0] = 11
print(id(arr), arr[0,0])

1
140659902935760 11


In [7]:
arr_3d = np.reshape(arr, (2, 3 , 2))
print(id(arr_3d), arr_3d)

140659890555088 [[[11  5]
  [ 4  5]
  [ 3  7]]

 [[ 8  7]
  [ 4  9]
  [ 4  6]]]


In [11]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 1
a

ValueError: assignment destination is read-only

In [15]:
p = [[1, 5, 4, 5],
 [3, 7, 8, 7],
 [4, 9, 4, 6]]
arr = np.array(p)
print("BEFORE RESHAPE: address:", id(arr), arr) # id is the object's memory address

arr_3d = np.reshape(arr, (2, 3 , 2))
print("AFTER RESHAPE: address:", id(arr_3d), arr_3d)

BEFORE RESHAPE: address: 140659906049392 [[1 5 4 5]
 [3 7 8 7]
 [4 9 4 6]]
AFTER RESHAPE: address: 140659906912496 [[[1 5]
  [4 5]
  [3 7]]

 [[8 7]
  [4 9]
  [4 6]]]


In [19]:
arr[1,1]

7

In [24]:
arr[:2,-2:]

array([[4, 5],
       [8, 7]])

In [25]:
np.arange(1,16,2).reshape(4, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [18]:
l1 = [1 ,2, 3, 4]
print(id(l1), len(l1), l1)
l1.append(5)
print(id(l1), len(l1), l1)

140659886765232 4 [1, 2, 3, 4]
140659886765232 5 [1, 2, 3, 4, 5]


In [26]:
'''
Print "+"
Description
Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.
Hint: Start by creating a (n x n) array with all zeroes using the np.zeros() function and then fill in the ones at the appropriate indices. Use integer division (//) to access the middle rows and columns
Examples:
Input 1:
3

Output 1:
[[0 1 0]
 [1 1 1]
 [0 1 0]]

Input 2:
5

Output 1:
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]

Explanation: Notice that the 1s in the arrays make a shape like '+'.
'''

In [38]:
n = 5 
arr = np.zeros((n,n),dtype=int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [39]:
mid = n//2
arr[:, mid] = 1
arr[mid, :] = 1
arr

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

In [9]:
import numpy as np
x = [[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]];print(x)
xarr = np.array(x)
print(xarr)
xarr[0], xarr[:,-1], xarr[-1], xarr[:, 0]

[[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


(array([11, 12, 13, 14]),
 array([14, 24, 34]),
 array([31, 32, 33, 34]),
 array([11, 21, 31]))

In [18]:
np.random.randint(7, size=[3, 4])

array([[5, 3, 0, 4],
       [5, 5, 3, 0],
       [0, 2, 2, 2]])