## Extracting Elements from Array
Description
From a given array, extract all the elements which are greater than 'm' and less than 'n'. Note: 'm' and 'n' are integer values provided as input.

Input format:
A list of integers on line one
Integer 'm' on line two
Integer 'n' on line three

Output format:
1-D array containing integers greater than 'm' and smaller than 'n'.

Sample input:

[ 1, 5, 9, 12, 15, 7, 12, 9 ] (array)

6 (m)

12 (n)

Sample output:[ 9 7 9 ]

Sample input:

[ 1, 5, 9, 12, 15, 7, 12, 9 ]

12

6

Sample output:[ ]

In [5]:
import ast
import numpy as np

In [8]:
values = [ 1, 5, 9, 12, 15, 7, 12, 9 ] #ast.literal_eval(input())
m, n = 6, 12
arr = np.array(values)
print(arr)
print(arr[(arr>m) & (arr<n)])

[ 1  5  9 12 15  7 12  9]
[9 7 9]


## Border Rows and Columns
Extract all the border rows and columns from a 2-D array.

Format:
Input: A 2-D Python list

Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.

Example:

Input 1:
[[11 12 13 14]

 [21 22 23 24]

 [31 32 33 34]]

Output 1:
[11 21 31]

[11 12 13 14]

[14 24 34]

[31 32 33 34]

In [11]:
arr = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(arr)

print("First column:", arr[:,0])
print("First row:", arr[0,:])
print("Last row:", arr[-1,:])
print("Last column:", arr[:,-1])

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
First column: [11 21 31]
First row: [11 12 13 14]
Last row: [31 32 33 34]
Last column: [14 24 34]


# Array 'arange' Function
Create an array of first 10 multiples of 5 using the 'arange' function.

In [13]:
np.arange(5, 5*10+1, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

## Create border array
Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

Note: Make sure the array is of type int.

Example:

Input 1: 4

Output 1:

[[1 1 1 1]

[1 0 0 1]

[1 0 0 1]

[1 1 1 1]]

Input 2: 2

Output 2:

[[1 1] 

 [1 1]] 

In [23]:
n = 6
arr = np.ones((n,n))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Merge the three arrays provided to you to form a one 4x4 array.

[Hint: Check the function np.transpose() in the 'Manipulating Arrays' notebook provided.]

Input:

Array 1: 3*3

[[7, 13, 14]

[18, 10, 17]

[11, 12, 19]]

Array 2: 1-D array

[16, 6, 1]

Array 3: 1*4 array

[[5, 8, 4, 3]]

Output:

[[7 13 14 5]

[18 10 17 8]

[11 12 19 4]

[16 6 1 3]]

In [45]:
arr1 = np.array([[7, 13, 14], [18, 10, 17], [11, 12, 19]])
arr2 = np.array([16, 6, 1])
arr3 = np.array([[5, 8, 4, 3]])

arr2 = arr2.reshape(1, 3)
arr4 = np.vstack((arr1, arr2.reshape(1, 3)))
print(arr4)

arr3 = arr3.reshape(4, 1)
print(arr3)

arr4 = np.hstack((arr4, arr3))
print(arr4)

[[ 7 13 14]
 [18 10 17]
 [11 12 19]
 [16  6  1]]
[[5]
 [8]
 [4]
 [3]]
[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


In [46]:
y = np.empty(5)
y   

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])